config/routes.rb
Rails.application.routes.draw do
  root "categories#index"

  get 'bookmarks/new'
  get 'bookmarks/create'
  get 'bookmarks/destroy'
  get 'categories/index'
  get 'categories/show'
  get 'categories/new'
  get 'categories/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  get "up" => "rails/health#show", as: :rails_health_check

    resources :categories, only: [:index, :show, :new, :create] do
      resources :bookmarks, only: [:new, :create]
    end

    resources :bookmarks, only: [:destroy]
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :recipe
  belongs_to :category

  validates :category_id, uniqueness: { scope: :recipe_id }
  validates :comment, length: { minimum: 6 }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :recipes, through: :bookmarks

  validates :name, uniqueness: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
has_many :bookmarks

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :rating, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @bookmark = Bookmark.new
  end

  def create
    @category = Category.find(params[:category_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.category = @category

    if @bookmark.save
      redirect_to category_path(@category), notice: "Recipe added!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    category = @bookmark.category
    @bookmark.destroy
    redirect_to category_path(category), notice: "Recipe removed."
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :recipe_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/bookmarks/new.html.erb
<div class="form-new mt-5">
  <h1>Add a Recipe to <%= @category.name %> category</h1>

  <%= simple_form_for [@category, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :recipe %>
    <%= f.button :submit, "Add Recipe" %>
  <% end %>

  <%= link_to "Back to #{@category.name}", category_path(@category) %>
</div>

app/views/categories/index.html.erb
<div class="banner" style="background-image: url('<%= image_path("banner1.png") %>')">
  <div>
    <h1>CookBook</h1>
    <h3>Save your favourite recipes</h3>
  </div>
</div>

<div class="container w-75">
  <div class="info-top">
    <h2>List of Categories</h2>
    <%= link_to 'New category', new_category_path, class: "btn btn-warning" %>
  </div>

  <div class="cards">
    <% @categories.each do |category| %>
      <%= link_to category_path(category) do %>
        <div class="card-category" style="background-image: url('<%= image_path("banner1.png") %>')">
          <h3><%= category.name %></h3>
          <p><%= category.bookmarks.count %> recipes</p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="form-new mt-5">
  <h1>New Category</h1>

  <%= simple_form_for @category do |f| %>
    <%= f.input :name %>
    <%= f.button :submit, "Create Category" %>
  <% end %>
  <%= link_to 'Back to home', categories_path %>

</div>

app/views/categories/show.html.erb
<div class="banner" style="background-image: url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
  <h1><%= @category.name %></h1>
</div>

  <div class="container w-75">
    <div class="info-top">
      <h2>Recipes</h2>
      <%= link_to "Add a recipe", new_category_bookmark_path(@category), class: "btn btn-warning" %>
    </div>

    <div class="cards">
      <% @category.bookmarks.each do |bookmark| %>
        <div class="card-trip">
           <%= link_to bookmark_path(bookmark),
                      data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                      class: "btn-delete" do %>
                      <i class="fa-solid fa-trash"></i>
           <% end %>
          <img src="<%= bookmark.recipe.image_url %>" />
          <div class="card-trip-description">
            <h3><%= bookmark.recipe.name %></h3>
            <p><%= bookmark.recipe.description.truncate(100) %></p>
          </div>

          <div class="card-trip-infos">
            <div>
              <p><%= bookmark.comment %></p>
            </div>
            <div>
              <%= bookmark.recipe.rating %> ★ <%= bookmark.recipe.rating.floor %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <%= link_to 'Add a recipe', new_category_bookmark_path(@category) %>
  <%= link_to 'Home', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCookbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <%= image_tag 'logo.png' %>

  <div>
    <%= link_to 'Home', root_path %>
    <%= link_to 'New Category', new_category_path %>
  </div>
</div>